name: CI

on:
  push:
    branches: [main]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python -m venv .venv
      - run: python -m pip install -r requirements.txt
      - run: pytest -v
